### PR TITLE
ignore non-JSON API requests

### PR DESCRIPTION
**Pull request by gr2m**
workaround for #6

### CODE REVIEW

**Comment by wraithgar** [comment]
Looks good to me, ship it, with a test if you want to (I will try to get to it if you don't want to do that).

**Comment by wraithgar** [comment]
Patch release imo.

**Comment by gr2m** [comment]
Nice thanks, I'll update the PR with a nest, thanks Gar :)

**Comment by gr2m** [comment]
args sorry, accidentally pushed to master now. Oh man, this usually does not happen to me :/

But I think the commits are ok: 
1. 6245f4e
2. 2705bb1

Let me know if you want anything changed

**Comment by gr2m** [comment]
if it looks good to you, I can do the release, otherwise let me know and I get it fixed first. Sorry again :(

**Comment by wraithgar** [comment]
Oh hey yeah an internals function, very nice. Ship it.  Thank you so much.

**Comment by gr2m** [comment]
done :tada: 

I've added [semantic-release](https://github.com/semantic-release/semantic-release) to all my repos, it automatically publishes new versions based on the commit messages via travis, and also creates tags & releases on Github. Setup is super easy: https://github.com/semantic-release/semantic-release#setup

Highly recommended :) You will never look back, word on that. Happy to help with any questions you have on semantic-release

**Pull request closed without merging**
